# Secrets (Use ansible-vault encrypt to secure this file)
hcloud_token: "YOUR_HCLOUD_TOKEN"
restic_password: "A_VERY_STRONG_PASSWORD"
pocket_id_client_secret: "ANOTHER_SECRET"
# Add other secrets here
